/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uwko8Exzhr8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"

export function SecondPage() {
  return (
    <div className="bg-background text-foreground">
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Journey & Inspiration</h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Discover the story behind our company and the inspirations that drive us forward.
              </p>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#5DB661] px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#5DB661]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="310"
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Milestones & Inspirations</h2>
            <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore the key moments and inspirations that have shaped our journey.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-12">
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Milestone"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Founding</h3>
                <p className="text-muted-foreground">
                  Our company was founded in 2015 with a mission to revolutionize the way businesses approach
                  technology.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Inspiration"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Sustainable Design</h3>
                <p className="text-muted-foreground">
                  We are inspired by the principles of sustainable design, which guide our product development and
                  operations.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Milestone"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Global Expansion</h3>
                <p className="text-muted-foreground">
                  In 2020, we expanded our reach to serve customers across the globe, bringing our innovative solutions
                  to new markets.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Inspiration"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Customer-Centricity</h3>
                <p className="text-muted-foreground">
                  Our unwavering focus on customer satisfaction has been a driving force behind our success and growth.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Milestone"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Technological Innovation</h3>
                <p className="text-muted-foreground">
                  Our commitment to innovation has led us to develop cutting-edge technologies that empower our clients
                  to achieve their goals.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Inspiration"
                className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
              />
              <CardContent className="p-6 space-y-2">
                <h3 className="text-xl font-bold">Collaborative Culture</h3>
                <p className="text-muted-foreground">
                  Our diverse and talented team works together to create solutions that make a real difference for our
                  clients.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
