/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EOf87SHc3Sg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 **/

export function ThirdPage() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-white">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="space-y-4 text-center">
          {/* Centered Heading */}
          <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl text-black bg-white py-4 px-6 rounded-lg mx-auto max-w-fit font-['Roboto', 'sans-serif']">
            Our journey so far
          </h2>
          {/* Centered Subheading */}
          <p className="mx-auto max-w-[700px] text-xl text-gray-600 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Explore the key milestones that have shaped our company over the
            years.
          </p>
        </div>
        <div className="mt-12">
          <div className="grid gap-8">
            <div className="relative grid grid-cols-[60px_1fr] gap-6 after:absolute after:inset-y-0 after:left-[30px] after:h-full after:w-px after:bg-muted-foreground/20">
              <div className="flex flex-col items-center gap-2">
                <div className="aspect-square w-10 rounded-full bg-[#5DB661]" />
                <div className="h-full w-px bg-muted-foreground/20" />
              </div>
              <div>
                <div className="text-lg font-semibold text-black">
                  Launched our first product
                </div>
                <div className="text-xs text-muted-foreground">
                  January 15, 2020
                </div>
                <p className="text-sm text-muted-foreground">
                  We launched our first product, a web-based application that
                  revolutionized the way our customers managed their data.
                </p>
              </div>
            </div>
            <div className="relative grid grid-cols-[60px_1fr] gap-6 after:absolute after:inset-y-0 after:left-[30px] after:h-full after:w-px after:bg-muted-foreground/20">
              <div className="flex flex-col items-center gap-2">
                <div className="aspect-square w-10 rounded-full bg-[#5DB661]" />
                <div className="h-full w-px bg-muted-foreground/20" />
              </div>
              <div>
                <div className="text-lg font-semibold text-black">
                  Opened our first office
                </div>
                <div className="text-xs text-muted-foreground">
                  June 1, 2021
                </div>
                <p className="text-sm text-muted-foreground">
                  We opened our first office in the heart of the city, providing
                  a space for our growing team to collaborate and innovate.
                </p>
              </div>
            </div>
            <div className="relative grid grid-cols-[60px_1fr] gap-6 after:absolute after:inset-y-0 after:left-[30px] after:h-full after:w-px after:bg-muted-foreground/20">
              <div className="flex flex-col items-center gap-2">
                <div className="aspect-square w-10 rounded-full bg-[#5DB661]" />
                <div className="h-full w-px bg-muted-foreground/20" />
              </div>
              <div>
                <div className="text-lg font-semibold text-black">
                  Reached 1,000 customers
                </div>
                <div className="text-xs text-muted-foreground">
                  September 30, 2022
                </div>
                <p className="text-sm text-muted-foreground">
                  We celebrated a major milestone as we reached 1,000 customers,
                  solidifying our position as a leading provider in our
                  industry.
                </p>
              </div>
            </div>
            <div className="relative grid grid-cols-[60px_1fr] gap-6 after:absolute after:inset-y-0 after:left-[30px] after:h-full after:w-px after:bg-muted-foreground/20">
              <div className="flex flex-col items-center gap-2">
                <div className="aspect-square w-10 rounded-full bg-[#5DB661]" />
                <div className="h-full w-px bg-muted-foreground/20" />
              </div>
              <div>
                <div className="text-lg font-semibold text-black">
                  Launched our mobile app
                </div>
                <div className="text-xs text-muted-foreground">
                  April 1, 2023
                </div>
                <p className="text-sm text-muted-foreground">
                  We expanded our product offerings by launching a mobile app,
                  allowing our customers to access our services on the go.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
